<a href="https://colab.research.google.com/github/dafeRoy/pytorch_intro/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
import torch
import numpy as np

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.10379966, 0.81538368, 0.17560223, 0.4757772 ],
       [0.74565567, 0.76888102, 0.42463941, 0.54488149],
       [0.53300037, 0.05183067, 0.71629778, 0.67951645]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
tensor1 = torch.randn(3,4)
tensor1

tensor([[-0.2217,  1.7585,  0.5418,  1.5206],
        [-1.9007, -1.9255,  0.2600,  2.2420],
        [-1.5793, -0.0323,  0.0945, -0.1252]])

In [9]:
tensor1.dtype

torch.float32

In [10]:
tensor2 = torch.zeros(2,3,4)
tensor2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# create tensor from numpy array
tensor3 = torch.from_numpy(np1)
tensor3

tensor([[0.1038, 0.8154, 0.1756, 0.4758],
        [0.7457, 0.7689, 0.4246, 0.5449],
        [0.5330, 0.0518, 0.7163, 0.6795]], dtype=torch.float64)