<a href="https://colab.research.google.com/github/dafeRoy/pytorch_intro/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
op1 = torch.arange(10)
op1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# reshape and view
op2 = op1.reshape(2,5)
op2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# reshape not knowing number of items using -1
op3 = op1.reshape(2,-1) # or (-1,5)
op3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# google difference between shape and view in pytorch

In [8]:
# reshape and view updates with change in original array
op4 = torch.arange(10)
op4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
op5 = op4.reshape(2,5)
op5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
op4[1] = 4141
op5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [11]:
# slicing

In [12]:
# grab a specific item
op4[7]

tensor(7)

In [13]:
# grab slice
op4[2:7]

tensor([2, 3, 4, 5, 6])

In [14]:
op6 = op4.reshape(5,2)
op6

tensor([[   0, 4141],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [15]:
op6[:,1]

tensor([4141,    3,    5,    7,    9])

In [16]:
# to return column
op6[:,1:]

tensor([[4141],
        [   3],
        [   5],
        [   7],
        [   9]])