<a href="https://colab.research.google.com/github/dafeRoy/pytorch_intro/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])

In [4]:
# addition
tensor1 + tensor2

tensor([5, 7, 9])

In [5]:
# addition longhand
torch.add(tensor1, tensor2) # tensor1.add(tensor2)

tensor([5, 7, 9])

In [6]:
# subtraction
tensor2 - tensor1 # torch.sub(tensor2 -tensor1) # tensor2.sub(tensor1)

tensor([3, 3, 3])

In [7]:
# multiplication
tensor1 * tensor2 # torch.mul(tensor1, tensor2)

tensor([ 4, 10, 18])

In [8]:
# division
tensor2 / tensor1 # torch.div(tensor2, tensor1)

tensor([4.0000, 2.5000, 2.0000])

In [9]:
# remainder
tensor2 % tensor1 # torch.remainder(tensor2, tensor1)

tensor([0, 1, 0])

In [10]:
# exponentials
tensor1 ** tensor2 # torch.pow(tensor1, tensor2)

tensor([  1,  32, 729])

In [11]:
# reassignment_
tensor1.add_(tensor2)

tensor([5, 7, 9])